version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-core-utils
    versions:
    - 2.3.0
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 3.3.1
  - dependency-name: core-js
    versions:
    - 3.11.0
  - dependency-name: gatsby-background-image
    versions:
    - 1.5.2
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.0
    - 2.32.2
    - 2.32.3
    - 2.32.4
    - 2.32.5
    - 2.32.8
    - 2.32.9
    - 3.2.0
    - 3.2.1
    - 3.3.0
    - 3.3.1
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.1
    - 5.20.2
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.26.0
    - 5.31.0
    - 5.33.2
    - 5.35.0
  - dependency-name: gatsby-plugin-image
    versions:
    - 1.3.0
  - dependency-name: twin.macro
    versions:
    - 2.3.2
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: gatsby-plugin-styled-components
    versions:
    - 3.10.0
    - 3.9.0
    - 4.2.0
    - 4.3.0
  - dependency-name: tailwindcss
    versions:
    - 2.1.0
  - dependency-name: cypress
    versions:
    - 6.1.0
    - 6.7.0
  - dependency-name: gatsby-image
    versions:
    - 2.10.0
    - 2.11.0
    - 3.0.0
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.9.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.10.0
    - 2.11.0
    - 2.11.1
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.10.0
    - 3.9.0
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.11.0
    - 2.12.0
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: styled-components
    versions:
    - 5.2.1
  - dependency-name: eslint-config-prettier
    versions:
    - 6.15.0
  - dependency-name: object-path
    versions:
    - 0.11.5
