version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '09:00'
      timezone: 'Australia/Brisbane'
    versioning-strategy: 'increase'
    target-branch: 'main'
    labels:
      - 'npm dependencies'
