name: Cypress

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress
        uses: cypress-io/github-action@v4
        with:
          record: true
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000/ping'
          wait-on-timeout: 10
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
